<?php

// uncomment the following to define a path alias
// Yii::setPathOfAlias('local','path/to/local-folder');

// This is the main Web application configuration. Any writable
// CWebApplication properties can be configured here.

return array(
        'basePath'=>dirname(__FILE__).DIRECTORY_SEPARATOR.'..',
        'name'=>'PurplePier',

        // preloading 'log' component
        'preload'=>array('log'),
    
        'language'=>'pt',

        // autoloading model and component classes
        'import'=>array(
                'application.models.*',
                'application.components.*',
                'application.helpers.*',
                'ext.vendors.FirePHPCore.*',
                'ext.utils.MethodUtils',
                'ext.utils.HelperUtils',
                'ext.utils.constants.*',
                'ext.digitalbuzz.activityLogger.*',
                'webroot.media.user.files.Settings'
        ),

        // application components
        'components'=>array(
                'maintenanceMode' => array(
                'class' => 'ext.vendors.maintenanceMode.MaintenanceMode',
                'enabledMode' => false,
                // redirect all requests to this controller/action for maintenance page
                'capUrl' => 'manutencao',
                // allowed users
                'users' => array(
                    'contato@purplepier.com.br',
                ),
                // allowed urls
                'urls' => array('/admin/login'),
                ),
                'user'=>array(
                // enable cookie-based authentication
                    'allowAutoLogin'=>true
                ),
              
            
                'twitter' => array(
                    'class' => 'application.extensions.vendors.twitter.STwitter',
                    'signinParams' => array('force_write'),
                ),
            
                // uncomment the following to enable URLs in path-format
		'urlManager'=>array(
			'urlFormat'=>'path',
                        'showScriptName' => false,
			'rules'=>array(
                            'home'                                                      => 'site/home', 
                            'email'                                                     => 'email',
                            'email/<action:\w+>'                                        => 'email',
                            'submit'                                                    => 'submit',
                            'submit/<action:\w+>'                                       => 'submit',
                            'buscar'                                                    => 'buscar',
                            'buscar/<action:\w+>'                                       => 'buscar',
                            'buscar/<action:\w+>/<search>'                              => 'buscar',                             
                          
                            'loja'                                                      => 'loja',
                            'loja/<action>'                                             => 'loja',
                            'loja/<action:\w+>/<cat\w+>'                                => 'loja',
                            'loja/<action:\w+>/<cat\w+>/<sub>'                          => 'loja',
                            'loja/<action:\w+>/<cat\w+>/<sub>/<subitem>'                => 'loja',
                            'loja/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>'           => 'loja',
                            'loja/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>/<init>'    => 'loja',
                            'loja/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>/<final>'   => 'loja',
                            
                            'produtos'                                                    => 'produtos',
                            'produtos/<action>'                                           => 'produtos',
                            'produtos/<action:\w+>/<cat\w+>'                              => 'produtos',
                            'produtos/<action:\w+>/<cat\w+>/<sub>'                        => 'produtos',
                            'produtos/<action:\w+>/<cat\w+>/<sub>/<subitem>'              => 'produtos',
                            'produtos/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>'         => 'produtos',
                            'produtos/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>/<init>'  => 'produtos',
                            'produtos/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>/<final>' => 'produtos',
                            
                            'autos'                                                       => 'autos',
                            'autos/<action>'                                              => 'autos',
                            'autos/<action:\w+>/<cat\w+>'                                 => 'autos',
                            'autos/<action:\w+>/<cat\w+>/<sub>'                           => 'autos',
                            'autos/<action:\w+>/<cat\w+>/<sub>/<subitem>'                 => 'autos',
                            'autos/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>'            => 'autos',
                            'autos/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>/<init>'     => 'autos',
                            'autos/<action:\w+>/<cat\w+>/<sub>/<subitem>/<id>/<final>'    => 'autos',
                            
                            'pagamento'                                                 => 'pagamento',
                            'pagamento/<action>'                                        => 'pagamento',
                            'pagamento/<action:\w+>/<tipo\w+>'                          => 'pagamento',
                            
                            
                            'cep'                                                       => 'cep',
                            'cep/<action:\w+>'                                          => 'cep',
                            
                            'user'                                                      => 'user',
                            'user/<action:\w+>'                                         => 'user',
                            
                            
                            
                            'cadastrar'                                                 => 'cadastrar',
                            'cadastrar/<action:\w+>'                                    => 'cadastrar',
                            'cadastrar/<action:\w+>/<id>'                               => 'cadastrar',
                            
                            'login'                                                     => 'login',
                            'login/<action:\w+>'                                        => 'login',
                            'login/<action:\w+>/<cat\w+>'                               => 'login',
                            'sejafornecedor'                                            => 'sejafornecedor',
                            'sejafornecedor/<action:\w+>'                                => 'sejafornecedor',
                         
                            'revista'                                                   => 'revista',
                            'revista/<action:\w+>'                                      => 'revista',
                            'revista/<action:\w+>/<id>'                                 => 'revista',
                            'pedidos'                                                   => 'pedidos',
                            'pedidos/<action:\w+>'                                      => 'pedidos',
                            'pedidos/<action:\w+>/<event:\w+>'                          => 'pedidos',
                            'pedidos/<action:\w+>/<event:\w+>/<id>'                     => 'pedidos',
                            'propostas'                                                 => 'propostas',
                            'propostas/<action:\w+>'                                    => 'propostas',
                            'propostas/<action:\w+>/<id>'                               => 'propostas',
                            'playground'                                                => 'playground',
                            'playground/<action:\w+>'                                   => 'playground',
                            'playground/<action:\w+>/<id>'                              => 'playground',
                            'chamados'                                                  => 'chamados',
                            'chamados/<action:\w+>'                                     => 'chamados',
                            'chamados/<action:\w+>/<id>'                                => 'chamados',
                            'conta'                                                     => 'conta',
                            'conta/<tipo:\w+>'                                          => 'conta',
                            'conta/<tipo:\w+>/<action:\w+>/<event>'                     => 'conta',
                            'conta/<tipo:\w+>/<action:\w+>/<event><id>'                 => 'conta',
                            'regiao'                                                    => 'regiao',
                            'regiao/<action:\w+>'                                       => 'regiao',
                            'regiao/<action:\w+>/<id>'                                  => 'regiao',
                            'forum'                                                     => 'forum',
                            'forum/<action:\w+>'                                        => 'forum',
                            'forum/<action:\w+>/<id>'                                   => 'forum',
                            'downloads'                                                 => 'downloads',
                            'downloads/<action:\w+>'                                    => 'downloads',
                            'downloads/<action:\w+>/<id>'                               => 'downloads',
                            'lnk'                                                       => 'lnk',
                            'lnk/<action:\w+>'                                          => 'lnk',
                            'lnk/<action:\w+>/<id>'                                     => 'lnk',
                            'users'                                                     => 'users',
                            'users/<action:\w+>'                                        => 'users',
                            'users/<action:\w+>/<event>'                                => 'users',
                            'users/<action:\w+>/<event>/<id>'                           => 'users',
                            'banners'                                                   => 'htmlbanners',
                            'banners/<action:\w+>'                                      => 'htmlbanners',
                            'banners/<action:\w+>/<event>'                              => 'htmlbanners',
                            'banners/<action:\w+>/<event>/<id>'                         => 'htmlbanners',
                            'bancodecurriculos'                                         => 'bancocurriculos',
                            'bancodecurriculos/<action:\w+>'                            => 'bancocurriculos',
                            'bancodecurriculos/<action:\w+>/<type>'                     => 'bancocurriculos',
                            'bancodecurriculos/<action:\w+>/<type>/<id>'                => 'bancocurriculos',
                            
                            'wiki'                                                      => 'wiki',
                            'wiki/<action:\w+>'                                         => 'wiki',
                            'wiki/<action:\w+>/<id>'                                    => 'wiki',
                            'wiki/<action:\w+>/<id>/<url>'                              => 'wiki',
                            
                            'eventos'                                                   => 'eventos',
                            'eventos/<action:\w+>'                                      => 'eventos',                            
                            'eventos/<action:\w+>/<id>'                                 => 'eventos',
                            
                            'galeria'                                                   => 'galeria',
                            'galeria/<action:\w+>'                                      => 'galeria',                            
                            'galeria/<action:\w+>/<type>'                               => 'galeria',
                            'galeria/<action:\w+>/<type>/<id>'                          => 'galeria',
                            
                            'app'                                                       => 'app',
                            'app/<action:\w+>'                                          => 'app',                            
                            'app/<action:\w+>/<id>'                                     => 'app',
                            
                            'pesquisas'                                                 => 'pesquisas',
                            'pesquisas/<action:\w+>'                                    => 'pesquisas',                            
                            'pesquisas/<action:\w+>/<id>'                               => 'pesquisas',
                            
                            'emkt'                                                      => 'emkt',
                            'emkt/<action:\w+>'                                         => 'emkt',
                            'emkt/<action:\w+>/<type>'                                  => 'emkt',
                            
                            'pagamento'                                                 => 'pagamento',
                            'pagamento/<action:\w+>'                                    => 'pagamento',                            
                            'pagamento/<action:\w+>/<event>'                            => 'pagamento',
                            'rss'                                                       => 'site/rss',
                            'controle'                                                  => 'controle/content',
                            'controle/<sub:\w+>'                                        => 'controle/content',    
                            'controle/<sub:\w+>/<action:\w+>'                           => 'controle/content',                            
                            'controle/<sub:\w+>/<action:\w+>/<id>'                      => 'controle/content',
                            'controle/<sub:\w+>/<action:\w+>/<id>/<url>'                => 'controle/content',
                            
                            'purplestore'                                               => 'purplestore',
                            'purplestore/<action:\w+>'                                  => 'purplestore',                            
                            'purplestore/<action:\w+>/<id>'                             => 'purplestore',
                            
                            'admin'                                                     => 'admin',
                            'admin/categorias/<action:\w+>'                             => 'admin/categorias',
                            'admin/categorias/<action:\w+>/<id:\d+>'                    => 'admin/categorias',
                            'admin/downloads/<action:\w+>'                              => 'admin/downloads',
                            'admin/downloads/<action:\w+>/<id:\d+>'                     => 'admin/downloads',
                            'admin/hiperlinks/<action:\w+>'                             => 'admin/hiperlinks',
                            'admin/hiperlinks/<action:\w+>/<id:\d+>'                    => 'admin/hiperlinks',
                            'admin/hotsite/<action:\w+>'                                => 'admin/hotsite',
                            'admin/hotsite/<action:\w+>/<id:\d+>'                       => 'admin/hotsite',
                            'admin/financeiro/<action:\w+>'                             => 'admin/financeiro',
                            'admin/financeiro/<action:\w+>/<id:\d+>'                    => 'admin/financeiro',
                            'admin/recursos_humanos/<user:\w+>/<action:\w+>'            => 'admin/recursos_humanos',
                            'admin/recursos_humanos/<user:\w+>/<action:\w+>/<id:\d+>'   => 'admin/recursos_humanos',
                            'admin/forca_vendas/<action:\w+>'                           => 'admin/forca_vendas',
                            'admin/forca_vendas/<action:\w+>/<id:\d+>'                  => 'admin/forca_vendas',
                            'admin/ordem_pedidos/<action:\w+>'                          => 'admin/ordem_pedidos',
                            'admin/ordem_pedidos/<action:\w+>/<id:\d+>'                 => 'admin/ordem_pedidos',
                            'admin/materias/<action:\w+>'                               => 'admin/materias',
                            'admin/materias/<action:\w+>/<id:\d+>'                      => 'admin/materias',
                            'admin/noticias/<action:\w+>'                               => 'admin/materias',
                            'admin/noticias/<action:\w+>/<id:\d+>'                      => 'admin/materias',
                            'admin/colunas/<action:\w+>'                                => 'admin/materias',
                            'admin/colunas/<action:\w+>/<id:\d+>'                       => 'admin/materias',
                            'admin/dicas/<action:\w+>'                                  => 'admin/materias',
                            'admin/dicas/<action:\w+>/<id:\d+>'                         => 'admin/materias',
                            'admin/wiki/<action:\w+>'                                   => 'admin/materias',
                            'admin/wiki/<action:\w+>/<id:\d+>'                          => 'admin/materias',
                            'admin/csseditor'                                           => 'csseditor',
                            'admin/csseditor/<action:\w+>'                              => 'csseditor',
                            
                            'admin/bkbank/<action:\w+>'                                 => 'admin/bkbank',
                            'admin/bkbank/<action:\w+>/<id:\d+>'                        => 'admin/bkbank',
                            
                            'admin/xml/<action:\w+>'                                    => 'admin/xml',
                            'admin/xml/<action:\w+>/<id:\d+>'                           => 'admin/xml',
                            
                            'admin/bancos/<action:\w+>'                                 => 'admin/bancos',
                            'admin/bancos/<action:\w+>/<id:\d+>'                        => 'admin/bancos',
                            
                            'admin/marketplace/<action:\w+>'                            => 'admin/marketplace',
                            'admin/marketplace/<action:\w+>/<id:\d+>'                   => 'admin/marketplace',
                            
                            'admin/marketplace2/<action:\w+>/<id:\d+>'                   => 'admin/marketplace2',
                            
                            
                            'admin/logos/<action:\w+>'                                  => 'admin/logos',
                            'admin/logos/<action:\w+>/<id:\d+>'                         => 'admin/logos',
                            'admin/beneficios'                                          => 'admin/beneficios',
                            'admin/beneficios/<action:\w+>'                             => 'admin/beneficios',
                            'admin/beneficios/<action:\w+>/<id>'                        => 'admin/beneficios',
                            'admin/promocao'                                            => 'admin/promocao',
                            'admin/promocao/<action:\w+>'                               => 'admin/promocao',
                            'admin/promocao/<action:\w+>/<id>'                          => 'admin/promocao',
                            'admin/purplestore'                                         => 'admin/purplestore',
                            'admin/purplestore/<action:\w+>'                            => 'admin/purplestore',
                            'admin/purplestore/<action:\w+>/<id>'                       => 'admin/purplestore',                            
                            'admin/calendario'                                          => 'admin/calendario',
                            'admin/calendario/<action:\w+>'                             => 'admin/calendario',
                            'admin/calendario/<action:\w+>/<event:\w+>'                 => 'admin/calendario',  
                            'admin/calendario/<action:\w+>/<event:\w+>/<id>'            => 'admin/calendario',
                            'admin/ping'                                                => 'admin/ping',
                            'admin/ping/<action:\w+>'                                   => 'admin/ping',
                            'admin/ping/<action:\w+>/<id>'                              => 'admin/ping',
                            'admin/novidades/<action:\w+>'                              => 'admin/materias',
                            'admin/novidades/<action:\w+>/<id:\d+>'                     => 'admin/materias',
                            'admin/blog/<action:\w+>'                                   => 'admin/materias',
                            'admin/blog/<action:\w+>/<id:\d+>'                          => 'admin/materias',
                            'admin/eventos/<action:\w+>'                                => 'admin/eventos',
                            'admin/eventos/<action:\w+>/<id:\d+>'                       => 'admin/eventos',
                            'admin/videos/<action:\w+>'                                 => 'admin/videos',
                            'admin/videos/<action:\w+>/<id>'                            => 'admin/videos',
                            'admin/banners/<size>'                                      => 'admin/banners',
                            'admin/banners/<size>/<action:\w+>'                         => 'admin/banners',
                            'admin/banners/<size>/<action:\w+>/<id:\d+>'                => 'admin/banners',
                            'admin/banners/<size>/<action:\w+>/<id:\d+>/<id_page:\d+>'  => 'admin/banners',
                            'admin/paginas/<action:\w+>'                                => 'admin/paginas',
                            'admin/paginas/<action:\w+>/<id>'                           => 'admin/paginas',
                            'admin/apostila/<action:\w+>'                               => 'admin/apostila',
                            'admin/apostila/<action:\w+>/<id>'                          => 'admin/apostila',
                            'admin/paginas_advanced/<action:\w+>'                       => 'admin/paginas_advanced',
                            'admin/paginas_advanced/<action:\w+>/<id>'                  => 'admin/paginas_advanced',
                            'admin/apostila_advanced/<action:\w+>'                      => 'admin/apostila_advanced',
                            'admin/apostila_advanced/<action:\w+>/<id>'                 => 'admin/apostila_advanced',
                            'admin/email/<action:\w+>'                                  => 'admin/email',
                            'admin/email/<action:\w+>/<id:\d+>'                         => 'admin/email',
                            'admin/newsletter/<action:\w+>'                             => 'admin/newsletter',
                            'admin/newsletter/<action:\w+>/<id:\d+>'                    => 'admin/newsletter',
                            'admin/galeria/<action:\w+>'                                => 'admin/galeria',
                            'admin/galeria/<action:\w+>/<id:\d+>'                       => 'admin/galeria',
                            'admin/galeria/<action:\w+>/<id:\d+>/<id_page:\d+>'         => 'admin/galeria',
                            'admin/images/<action:\w+>'                                 => 'admin/images',
                            'admin/images/<action:\w+>/<id>'                            => 'admin/images',
                            'admin/images/<action:\w+>/<id>/<id_page>'                  => 'admin/images',
                            'admin/cool/<action:\w+>'                                   => 'admin/cool',
                            'admin/cool/<action:\w+>/<id:\d+>'                          => 'admin/cool',
                            'admin/cool/<action:\w+>/<id:\d+>/<id_page:\d+>'            => 'admin/cool',
                            'admin/loja/<action:\w+>'                                   => 'admin/loja',
                            'admin/loja/<action:\w+>/<event>'                           => 'admin/loja',
                            'admin/loja/<action:\w+>/<event>/<id:\d+>'                  => 'admin/loja',
                            'admin/topos/<action:\w+>'                                  => 'admin/topos',
                            'admin/topos/<action:\w+>/<id:\d+>'                         => 'admin/topos',
                            'admin/rodapes/<action:\w+>'                                => 'admin/rodapes',
                            'admin/rodapes/<action:\w+>/<id:\d+>'                       => 'admin/rodapes',
                            'admin/vagas/<action:\w+>'                                  => 'admin/vagas',
                            'admin/vagas/<action:\w+>/<id:\d+>'                         => 'admin/vagas',
                            'admin/curriculums/<action:\w+>'                            => 'admin/curriculums',
                            'admin/curriculums/<action:\w+>/<id:\d+>'                   => 'admin/curriculums',
                            'admin/html_banners/<action:\w+>'                           => 'admin/html_banners',
                            'admin/html_banners/<action:\w+>/<id:\d+>'                  => 'admin/html_banners',
                            'admin/html_mainbanners/<action:\w+>'                       => 'admin/html_mainbanners',
                            'admin/html_mainbanners/<action:\w+>/<id:\d+>'              => 'admin/html_mainbanners',
                            'admin/html_spark/<action:\w+>'                             => 'admin/html_spark',
                            'admin/html_spark/<action:\w+>/<id:\d+>'                    => 'admin/html_spark',
                            'admin/html_corona/<action:\w+>'                            => 'admin/html_corona',
                            'admin/html_corona/<action:\w+>/<id:\d+>'                   => 'admin/html_corona',
                            'admin/html_mini/<action:\w+>'                              => 'admin/html_mini',
                            'admin/html_mini/<action:\w+>/<id:\d+>'                     => 'admin/html_mini',
                            'admin/html_lonsdale/<action:\w+>'                          => 'admin/html_lonsdale',
                            'admin/html_lonsdale/<action:\w+>/<id:\d+>'                 => 'admin/html_lonsdale',
                            'admin/html_blocks/<action:\w+>'                            => 'admin/html_blocks',
                            'admin/html_blocks/<action:\w+>/<id:\d+>'                   => 'admin/html_blocks',
                            'admin/html_renderpartial/<action:\w+>'                     => 'admin/html_renderpartial',
                            'admin/html_renderpartial/<action:\w+>/<id:\d+>'            => 'admin/html_renderpartial',
                            'admin/texturas/<type:\w+>'                                 => 'admin/texturas',
                            'admin/texturas/<type:\w+>/<action:\w+>'                    => 'admin/texturas',
                            'admin/texturas/<type:\w+>/<action:\w+>/<id:\d+>'           => 'admin/texturas',
                            'admin/texturas/<type:\w+>/<action:\w+>/<id:\d+>/<nr:\d+>'  => 'admin/texturas',
                            'admin/pesquisas/<action:\w+>'                              => 'admin/pesquisas',
                            'admin/pesquisas/<action:\w+>/<id:\d+>'                     => 'admin/pesquisas',
                            'admin/pesquisas/<action:\w+>/<id:\d+>/<nr:\d+>'            => 'admin/pesquisas',
                            'admin/mini_sites/<action:\w+>'                             => 'admin/mini_sites',
                            'admin/mini_sites/<action:\w+>/<id:\d+>'                    => 'admin/mini_sites',                           
                            'admin/avaliacao/<action:\w+>'                              => 'admin/avaliacao',
                            'admin/avaliacao/<action:\w+>/<id:\d+>'                     => 'admin/avaliacao',
                            'admin/avaliacao/<action:\w+>/<id:\d+>/<nr:\d+>'            => 'admin/avaliacao',
                            'admin/detalhes/<type:\w+>'                                 => 'admin/detalhes',
                            'admin/detalhes/<type:\w+>/<action:\w+>'                    => 'admin/detalhes',
                            'admin/detalhes/<type:\w+>/<action:\w+>/<id:\d+>'           => 'admin/detalhes',
                            'admin/fontes/<action:\w+>'                                 => 'admin/fontes',
                            'admin/layoutsite/<action:\w+>'                             => 'admin/layoutsite',
                            'admin/produtos'                                            => 'admin/produtos',
                            'admin/produtos/<action:\w+>'                               => 'admin/produtos',
                            'admin/produtos/<action:\w+>/<sub>'                         => 'admin/produtos',
                            'admin/produtos/<action:\w+>/<sub>/<id>'                    => 'admin/produtos',
                            'admin/ecommerce'                                           => 'admin/ecommerce',
                            'admin/ecommerce/<action:\w+>'                              => 'admin/ecommerce',
                            'admin/ecommerce/<action:\w+>/<sub>'                        => 'admin/ecommerce',
                            'admin/ecommerce/<action:\w+>/<sub>/<id>'                   => 'admin/ecommerce',
                            'admin/autos'                                               => 'admin/autos',
                            'admin/autos/<action:\w+>'                                  => 'admin/autos',
                            'admin/autos/<action:\w+>/<sub>'                            => 'admin/autos',
                            'admin/autos/<action:\w+>/<sub>/<id>'                       => 'admin/autos',
                            
                            'admin/elearn/<action:\w+>'                                 => 'admin/elearn',
                            'admin/elearn/<action:\w+>/<sub>'                           => 'admin/elearn',
                            'admin/elearn/<action:\w+>/<sub>/<id>'                      => 'admin/elearn',
                            
                            'admin/configurar/<action:\w+>'                             => 'admin/configurar',
                            'admin/configurar/<action:\w+>/<id:\d+>'                    => 'admin/configurar',
                            'admin/menu/'                                               => 'admin/menu',
                            'admin/menu/<action:\w+>'                                   => 'admin/menu',
                            'admin/menu/<action:\w+>/<id:\d+>'                          => 'admin/menu',
                            'admin/coolhtml/<action:\w+>'                               => 'admin/coolhtml',
                            'admin/coolhtml/<action:\w+>/<id>'                          => 'admin/coolhtml',
                            'admin/coolhtml/<action:\w+>/<id>/<start>'                  => 'admin/coolhtml',
                            'admin/coolhtml/<action:\w+>/<id>/<start>/<end>'            => 'admin/coolhtml',
                            'admin/logout'                                              => 'admin/logout',
                            'admin/logout/<action:\w+>'                                 => 'admin/logout',
                            'admin/login'                                               => 'admin/login',
                            'admin/login/<action:\w+>'                                  => 'admin/login',
                            'admin/documentacao/<action:\w+>'                           => 'admin/documentacao',
                            'admin/documentacao/<action:\w+>/<subaction:\w+>'           => 'admin/documentacao',
                            'admin/documentacao/<action:\w+>/<subaction:\w+>/<id>'      => 'admin/documentacao',
                            'admin/pedidos/<action:\w+>'                                => 'admin/pedidos',
                            'admin/pedidos/<action:\w+>/<type>'                         => 'admin/pedidos',
                            'admin/pedidos/<action:\w+>/<type>/<id>'                    => 'admin/pedidos',
                            'admin/userssupport'                                        => 'admin/userssupport',
                            'admin/userssupport/<action:\w+>'                           => 'admin/userssupport',
                            'admin/userssupport/<action:\w+>/<event>'                   => 'admin/userssupport',
                            'admin/userssupport/<action:\w+>/<event>/<id>'              => 'admin/userssupport',
                            'admin/users_selection'                                     => 'admin/users_selection',
                            'admin/users_selection/<action:\w+>'                        => 'admin/users_selection',
                            'admin/users_selection/<action:\w+>/<event>'                => 'admin/users_selection',
                            'admin/users_selection/<action:\w+>/<event>/<id>'           => 'admin/users_selection',
                            'conta/pedidos/<action:\w+>'                                => 'conta/pedidos',
                            'conta/pedidos/<action:\w+>/<type>'                         => 'conta/pedidos',
                            'conta/pedidos/<action:\w+>/<type>/<id>'                    => 'conta/pedidos',
                            'conta/orcamentus/<action:\w+>'                             => 'conta/orcamentus',
                            'conta/orcamentus/<action:\w+>/<id>'                        => 'conta/orcamentus',
                            'admin/users/<action:\w+>'                                  => 'admin/users',
                            'admin/users/<action:\w+>/<event:\w+>'                      => 'admin/users',
                            'admin/comentarios/<action:\w+>'                            => 'admin/comentarios',
                            'admin/comentarios/<action:\w+>/<id>'                       => 'admin/comentarios',
                            'admin/launcher3/<action:\w+>'                              => 'admin/launcher3',
                            'admin/launcher3/<action:\w+>/<id>'                         => 'admin/launcher3',
                            'admin/depoimentos/<action:\w+>'                            => 'admin/depoimentos',
                            'admin/depoimentos/<action:\w+>/<id>'                       => 'admin/depoimentos',
                            'admin/howto'                                               => 'admin/howto',
                            'admin/howto/<action:\w+>'                                  => 'admin/howto',
                            'admin/howto/<action:\w+>/<id:\d+>'                         => 'admin/howto',
                            'admin/dates'                                               => 'admin/dates',
                            'admin/dates/<action:\w+>'                                  => 'admin/dates',
                            'admin/dates/<action:\w+>/<id:\d+>'                         => 'admin/dates',
                            'admin/boletos'                                             => 'admin/boletos',
                            'admin/boletos/<action:\w+>'                                => 'admin/boletos',
                            'admin/boletos/<action:\w+>/<id:\d+>'                       => 'admin/boletos',
                            'admin/erp_categorias/<action:\w+>'                         => 'admin/erp_categorias',
                            'admin/erp_categorias/<action:\w+>/<id>'                    => 'admin/erp_categorias',
                            'admin/erp_categorias/<action:\w+>/<id>/<n2>'               => 'admin/erp_categorias',
                            'admin/erp_categorias/<action:\w+>/<id>/<n2>/<n3>'          => 'admin/erp_categorias',
                            'admin/erp_categorias/<action:\w+>/<id>/<n2>/<n3>/<n4>'     => 'admin/erp_categorias',
                            'admin/elearn'                                              => 'admin/elearn',
                            'admin/elearn/<action:\w+>'                                 => 'admin/elearn',
                            'admin/elearn/<action:\w+>/<event>'                         => 'admin/elearn',
                            'admin/elearn/<action:\w+>/<event>/<id>'                    => 'admin/elearn',
                            'admin/canal_comunicacao/<action:\w+>'                      => 'admin/canal_comunicacao',
                            'admin/canal_comunicacao/<action:\w+>/<id>'                 => 'admin/canal_comunicacao',
                            'admin/ticket/<action:\w+>'                                 => 'admin/ticket',
                            'admin/ticket/<action:\w+>/<id>'                            => 'admin/ticket',
                            'admin/mercadolivre/<action:\w+>'                           => 'admin/mercadolivre',
                            'admin/mercadolivre/<action:\w+>/<id>'                      => 'admin/mercadolivre',
                            'admin/intro/<action:\w+>'                                  => 'admin/intro',
                            'admin/intro/<action:\w+>/<id>'                             => 'admin/intro',
                            
                            '<nr:\w+>'                                                  => 'site/content',
                            '<nr:\w+>/<sub:\w+>'                                        => 'site/content',
                            '<nr:\w+>/<sub:\w+>/<action:\w+>'                           => 'site/content',
                            '<nr:\w+>/<sub:\w+>/<action:\w+>/<type>'                    => 'site/content',
                            '<nr:\w+>/<sub:\w+>/<action:\w+>/<type>/<id>'               => 'site/content',
			
                            ),
		),                

                'errorHandler'=>array(
                        // use 'site/error' action to display errors
                        'errorAction'=>'site/error',
                ),
                'log'=>array(
                        'class'=>'CLogRouter',
                        'routes'=>array(
                                array(
                                        'class'=>'CFileLogRoute',
                                        'levels'=>'trace, info, error, warning',
                                ),
                        
                        ),
                ),
        ),

        
);
